#!/bin/bash
set -e 

source CONFIG
source functions

ensure BASE NAME

echo "Setting up databases ..."

sed -i -r 's/(passwd|group):(.*)compat/\1:\2ldap files/g' ./${BASE}/${NAME}/etc/nsswitch.conf

if [ "$?" != "0" ]; then
    exit 1
fi

exit 0